### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by ayoubedd** [codam-coding-college/find-peers#6]
i had an issue today accessing the application.

### Output
```
TokenError: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
    at OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /app/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /app/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by SirMorfield** [comment]
Paris broke the credentials, problem has been fixed
